# Generated by Django 2.2.17 on 2020-11-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hello',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
